version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mysql:
        image: 'mysql:5.6'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        ports:
            - '5002:3306'

    clickhouse:
        image: 'yandex/clickhouse-server:latest'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
